/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SouscrireApeRouteImport } from './app/souscrire-ape'
import { Route as SetupPasswordRouteImport } from './app/setup-password'
import { Route as SamaNaffaRouteImport } from './app/sama-naffa'
import { Route as RegisterRouteImport } from './app/register'
import { Route as PeeRouteImport } from './app/pee'
import { Route as MaintenanceRouteImport } from './app/maintenance'
import { Route as LoginRouteImport } from './app/login'
import { Route as ForgotPasswordRouteImport } from './app/forgot-password'
import { Route as FaqRouteImport } from './app/faq'
import { Route as ContactRouteImport } from './app/contact'
import { Route as ApesenegalRouteImport } from './app/apesenegal'
import { Route as ApeRouteImport } from './app/ape'
import { Route as IndexRouteImport } from './app/index'
import { Route as PortalIndexRouteImport } from './app/portal/index'
import { Route as AdminIndexRouteImport } from './app/admin/index'
import { Route as PortalSamaNaffaRouteImport } from './app/portal/sama-naffa'
import { Route as PortalProfileRouteImport } from './app/portal/profile'
import { Route as PortalNotificationsRouteImport } from './app/portal/notifications'
import { Route as PortalDashboardRouteImport } from './app/portal/dashboard'
import { Route as PortalCompareRouteImport } from './app/portal/compare'
import { Route as PortalApeRouteImport } from './app/portal/ape'
import { Route as ApesenegalPaymentSuccessRouteImport } from './app/apesenegal/payment-success'
import { Route as ApesenegalPaymentStatusRouteImport } from './app/apesenegal/payment-status'
import { Route as ApesenegalPaymentFailedRouteImport } from './app/apesenegal/payment-failed'
import { Route as ApePaymentStatusRouteImport } from './app/ape/payment-status'
import { Route as AdminLoginRouteImport } from './app/admin/login'
import { Route as AdminLayoutRouteImport } from './app/admin/_layout'
import { Route as AdminUsersIndexRouteImport } from './app/admin/users/index'
import { Route as AdminTransactionsIndexRouteImport } from './app/admin/transactions/index'
import { Route as AdminSponsorCodesIndexRouteImport } from './app/admin/sponsor-codes/index'
import { Route as AdminSettingsIndexRouteImport } from './app/admin/settings/index'
import { Route as AdminReconciliationIndexRouteImport } from './app/admin/reconciliation/index'
import { Route as AdminNotificationsIndexRouteImport } from './app/admin/notifications/index'
import { Route as AdminKycIndexRouteImport } from './app/admin/kyc/index'
import { Route as AdminApeSubscriptionsIndexRouteImport } from './app/admin/ape-subscriptions/index'
import { Route as PortalSamaNaffaPaymentSuccessRouteImport } from './app/portal/sama-naffa/payment-success'
import { Route as PortalSamaNaffaPaymentFailedRouteImport } from './app/portal/sama-naffa/payment-failed'
import { Route as ApiAuthVerifyOtpRouteImport } from './app/api/auth/verify-otp'
import { Route as ApiAuthVerifyAndCreateAccountRouteImport } from './app/api/auth/verify-and-create-account'
import { Route as ApiAuthSignOutRouteImport } from './app/api/auth/sign-out'
import { Route as ApiAuthSetupPasswordRouteImport } from './app/api/auth/setup-password'
import { Route as ApiAuthSessionRouteImport } from './app/api/auth/session'
import { Route as ApiAuthSendOtpRouteImport } from './app/api/auth/send-otp'
import { Route as ApiAuthResetPasswordRouteImport } from './app/api/auth/reset-password'
import { Route as ApiAuthLoginRouteImport } from './app/api/auth/login'
import { Route as ApiAuthCheckAvailabilityRouteImport } from './app/api/auth/check-availability'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'
import { Route as AdminUsersIdRouteImport } from './app/admin/users/$id'
import { Route as AdminTransactionsIdRouteImport } from './app/admin/transactions/$id'
import { Route as AdminSponsorCodesIdRouteImport } from './app/admin/sponsor-codes/$id'
import { Route as AdminLeadsPeeRouteImport } from './app/admin/leads/pee'
import { Route as AdminLeadsAbandonedRouteImport } from './app/admin/leads/abandoned'
import { Route as AdminKycIdRouteImport } from './app/admin/kyc/$id'
import { Route as AdminApeSubscriptionsIdRouteImport } from './app/admin/ape-subscriptions/$id'

const SouscrireApeRoute = SouscrireApeRouteImport.update({
  id: '/souscrire-ape',
  path: '/souscrire-ape',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupPasswordRoute = SetupPasswordRouteImport.update({
  id: '/setup-password',
  path: '/setup-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SamaNaffaRoute = SamaNaffaRouteImport.update({
  id: '/sama-naffa',
  path: '/sama-naffa',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PeeRoute = PeeRouteImport.update({
  id: '/pee',
  path: '/pee',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApesenegalRoute = ApesenegalRouteImport.update({
  id: '/apesenegal',
  path: '/apesenegal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApeRoute = ApeRouteImport.update({
  id: '/ape',
  path: '/ape',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSamaNaffaRoute = PortalSamaNaffaRouteImport.update({
  id: '/portal/sama-naffa',
  path: '/portal/sama-naffa',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/portal/profile',
  path: '/portal/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalNotificationsRoute = PortalNotificationsRouteImport.update({
  id: '/portal/notifications',
  path: '/portal/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/portal/dashboard',
  path: '/portal/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCompareRoute = PortalCompareRouteImport.update({
  id: '/portal/compare',
  path: '/portal/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalApeRoute = PortalApeRouteImport.update({
  id: '/portal/ape',
  path: '/portal/ape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApesenegalPaymentSuccessRoute =
  ApesenegalPaymentSuccessRouteImport.update({
    id: '/payment-success',
    path: '/payment-success',
    getParentRoute: () => ApesenegalRoute,
  } as any)
const ApesenegalPaymentStatusRoute = ApesenegalPaymentStatusRouteImport.update({
  id: '/payment-status',
  path: '/payment-status',
  getParentRoute: () => ApesenegalRoute,
} as any)
const ApesenegalPaymentFailedRoute = ApesenegalPaymentFailedRouteImport.update({
  id: '/payment-failed',
  path: '/payment-failed',
  getParentRoute: () => ApesenegalRoute,
} as any)
const ApePaymentStatusRoute = ApePaymentStatusRouteImport.update({
  id: '/payment-status',
  path: '/payment-status',
  getParentRoute: () => ApeRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsIndexRoute = AdminTransactionsIndexRouteImport.update({
  id: '/admin/transactions/',
  path: '/admin/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSponsorCodesIndexRoute = AdminSponsorCodesIndexRouteImport.update({
  id: '/admin/sponsor-codes/',
  path: '/admin/sponsor-codes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/admin/settings/',
  path: '/admin/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReconciliationIndexRoute =
  AdminReconciliationIndexRouteImport.update({
    id: '/admin/reconciliation/',
    path: '/admin/reconciliation/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminNotificationsIndexRoute = AdminNotificationsIndexRouteImport.update({
  id: '/admin/notifications/',
  path: '/admin/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKycIndexRoute = AdminKycIndexRouteImport.update({
  id: '/admin/kyc/',
  path: '/admin/kyc/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApeSubscriptionsIndexRoute =
  AdminApeSubscriptionsIndexRouteImport.update({
    id: '/admin/ape-subscriptions/',
    path: '/admin/ape-subscriptions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalSamaNaffaPaymentSuccessRoute =
  PortalSamaNaffaPaymentSuccessRouteImport.update({
    id: '/payment-success',
    path: '/payment-success',
    getParentRoute: () => PortalSamaNaffaRoute,
  } as any)
const PortalSamaNaffaPaymentFailedRoute =
  PortalSamaNaffaPaymentFailedRouteImport.update({
    id: '/payment-failed',
    path: '/payment-failed',
    getParentRoute: () => PortalSamaNaffaRoute,
  } as any)
const ApiAuthVerifyOtpRoute = ApiAuthVerifyOtpRouteImport.update({
  id: '/api/auth/verify-otp',
  path: '/api/auth/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyAndCreateAccountRoute =
  ApiAuthVerifyAndCreateAccountRouteImport.update({
    id: '/api/auth/verify-and-create-account',
    path: '/api/auth/verify-and-create-account',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSetupPasswordRoute = ApiAuthSetupPasswordRouteImport.update({
  id: '/api/auth/setup-password',
  path: '/api/auth/setup-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSendOtpRoute = ApiAuthSendOtpRouteImport.update({
  id: '/api/auth/send-otp',
  path: '/api/auth/send-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResetPasswordRoute = ApiAuthResetPasswordRouteImport.update({
  id: '/api/auth/reset-password',
  path: '/api/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCheckAvailabilityRoute =
  ApiAuthCheckAvailabilityRouteImport.update({
    id: '/api/auth/check-availability',
    path: '/api/auth/check-availability',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/admin/users/$id',
  path: '/admin/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsIdRoute = AdminTransactionsIdRouteImport.update({
  id: '/admin/transactions/$id',
  path: '/admin/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSponsorCodesIdRoute = AdminSponsorCodesIdRouteImport.update({
  id: '/admin/sponsor-codes/$id',
  path: '/admin/sponsor-codes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsPeeRoute = AdminLeadsPeeRouteImport.update({
  id: '/admin/leads/pee',
  path: '/admin/leads/pee',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsAbandonedRoute = AdminLeadsAbandonedRouteImport.update({
  id: '/admin/leads/abandoned',
  path: '/admin/leads/abandoned',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKycIdRoute = AdminKycIdRouteImport.update({
  id: '/admin/kyc/$id',
  path: '/admin/kyc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApeSubscriptionsIdRoute = AdminApeSubscriptionsIdRouteImport.update({
  id: '/admin/ape-subscriptions/$id',
  path: '/admin/ape-subscriptions/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ape': typeof ApeRouteWithChildren
  '/apesenegal': typeof ApesenegalRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/pee': typeof PeeRoute
  '/register': typeof RegisterRoute
  '/sama-naffa': typeof SamaNaffaRoute
  '/setup-password': typeof SetupPasswordRoute
  '/souscrire-ape': typeof SouscrireApeRoute
  '/admin': typeof AdminLayoutRoute
  '/admin/login': typeof AdminLoginRoute
  '/ape/payment-status': typeof ApePaymentStatusRoute
  '/apesenegal/payment-failed': typeof ApesenegalPaymentFailedRoute
  '/apesenegal/payment-status': typeof ApesenegalPaymentStatusRoute
  '/apesenegal/payment-success': typeof ApesenegalPaymentSuccessRoute
  '/portal/ape': typeof PortalApeRoute
  '/portal/compare': typeof PortalCompareRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/sama-naffa': typeof PortalSamaNaffaRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/ape-subscriptions/$id': typeof AdminApeSubscriptionsIdRoute
  '/admin/kyc/$id': typeof AdminKycIdRoute
  '/admin/leads/abandoned': typeof AdminLeadsAbandonedRoute
  '/admin/leads/pee': typeof AdminLeadsPeeRoute
  '/admin/sponsor-codes/$id': typeof AdminSponsorCodesIdRoute
  '/admin/transactions/$id': typeof AdminTransactionsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/check-availability': typeof ApiAuthCheckAvailabilityRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/send-otp': typeof ApiAuthSendOtpRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/setup-password': typeof ApiAuthSetupPasswordRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/auth/verify-and-create-account': typeof ApiAuthVerifyAndCreateAccountRoute
  '/api/auth/verify-otp': typeof ApiAuthVerifyOtpRoute
  '/portal/sama-naffa/payment-failed': typeof PortalSamaNaffaPaymentFailedRoute
  '/portal/sama-naffa/payment-success': typeof PortalSamaNaffaPaymentSuccessRoute
  '/admin/ape-subscriptions/': typeof AdminApeSubscriptionsIndexRoute
  '/admin/kyc/': typeof AdminKycIndexRoute
  '/admin/notifications/': typeof AdminNotificationsIndexRoute
  '/admin/reconciliation/': typeof AdminReconciliationIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/sponsor-codes/': typeof AdminSponsorCodesIndexRoute
  '/admin/transactions/': typeof AdminTransactionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ape': typeof ApeRouteWithChildren
  '/apesenegal': typeof ApesenegalRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/pee': typeof PeeRoute
  '/register': typeof RegisterRoute
  '/sama-naffa': typeof SamaNaffaRoute
  '/setup-password': typeof SetupPasswordRoute
  '/souscrire-ape': typeof SouscrireApeRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/ape/payment-status': typeof ApePaymentStatusRoute
  '/apesenegal/payment-failed': typeof ApesenegalPaymentFailedRoute
  '/apesenegal/payment-status': typeof ApesenegalPaymentStatusRoute
  '/apesenegal/payment-success': typeof ApesenegalPaymentSuccessRoute
  '/portal/ape': typeof PortalApeRoute
  '/portal/compare': typeof PortalCompareRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/sama-naffa': typeof PortalSamaNaffaRouteWithChildren
  '/portal': typeof PortalIndexRoute
  '/admin/ape-subscriptions/$id': typeof AdminApeSubscriptionsIdRoute
  '/admin/kyc/$id': typeof AdminKycIdRoute
  '/admin/leads/abandoned': typeof AdminLeadsAbandonedRoute
  '/admin/leads/pee': typeof AdminLeadsPeeRoute
  '/admin/sponsor-codes/$id': typeof AdminSponsorCodesIdRoute
  '/admin/transactions/$id': typeof AdminTransactionsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/check-availability': typeof ApiAuthCheckAvailabilityRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/send-otp': typeof ApiAuthSendOtpRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/setup-password': typeof ApiAuthSetupPasswordRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/auth/verify-and-create-account': typeof ApiAuthVerifyAndCreateAccountRoute
  '/api/auth/verify-otp': typeof ApiAuthVerifyOtpRoute
  '/portal/sama-naffa/payment-failed': typeof PortalSamaNaffaPaymentFailedRoute
  '/portal/sama-naffa/payment-success': typeof PortalSamaNaffaPaymentSuccessRoute
  '/admin/ape-subscriptions': typeof AdminApeSubscriptionsIndexRoute
  '/admin/kyc': typeof AdminKycIndexRoute
  '/admin/notifications': typeof AdminNotificationsIndexRoute
  '/admin/reconciliation': typeof AdminReconciliationIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/sponsor-codes': typeof AdminSponsorCodesIndexRoute
  '/admin/transactions': typeof AdminTransactionsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ape': typeof ApeRouteWithChildren
  '/apesenegal': typeof ApesenegalRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/pee': typeof PeeRoute
  '/register': typeof RegisterRoute
  '/sama-naffa': typeof SamaNaffaRoute
  '/setup-password': typeof SetupPasswordRoute
  '/souscrire-ape': typeof SouscrireApeRoute
  '/admin/_layout': typeof AdminLayoutRoute
  '/admin/login': typeof AdminLoginRoute
  '/ape/payment-status': typeof ApePaymentStatusRoute
  '/apesenegal/payment-failed': typeof ApesenegalPaymentFailedRoute
  '/apesenegal/payment-status': typeof ApesenegalPaymentStatusRoute
  '/apesenegal/payment-success': typeof ApesenegalPaymentSuccessRoute
  '/portal/ape': typeof PortalApeRoute
  '/portal/compare': typeof PortalCompareRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/sama-naffa': typeof PortalSamaNaffaRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/ape-subscriptions/$id': typeof AdminApeSubscriptionsIdRoute
  '/admin/kyc/$id': typeof AdminKycIdRoute
  '/admin/leads/abandoned': typeof AdminLeadsAbandonedRoute
  '/admin/leads/pee': typeof AdminLeadsPeeRoute
  '/admin/sponsor-codes/$id': typeof AdminSponsorCodesIdRoute
  '/admin/transactions/$id': typeof AdminTransactionsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/check-availability': typeof ApiAuthCheckAvailabilityRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/send-otp': typeof ApiAuthSendOtpRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/setup-password': typeof ApiAuthSetupPasswordRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/auth/verify-and-create-account': typeof ApiAuthVerifyAndCreateAccountRoute
  '/api/auth/verify-otp': typeof ApiAuthVerifyOtpRoute
  '/portal/sama-naffa/payment-failed': typeof PortalSamaNaffaPaymentFailedRoute
  '/portal/sama-naffa/payment-success': typeof PortalSamaNaffaPaymentSuccessRoute
  '/admin/ape-subscriptions/': typeof AdminApeSubscriptionsIndexRoute
  '/admin/kyc/': typeof AdminKycIndexRoute
  '/admin/notifications/': typeof AdminNotificationsIndexRoute
  '/admin/reconciliation/': typeof AdminReconciliationIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/sponsor-codes/': typeof AdminSponsorCodesIndexRoute
  '/admin/transactions/': typeof AdminTransactionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ape'
    | '/apesenegal'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/pee'
    | '/register'
    | '/sama-naffa'
    | '/setup-password'
    | '/souscrire-ape'
    | '/admin'
    | '/admin/login'
    | '/ape/payment-status'
    | '/apesenegal/payment-failed'
    | '/apesenegal/payment-status'
    | '/apesenegal/payment-success'
    | '/portal/ape'
    | '/portal/compare'
    | '/portal/dashboard'
    | '/portal/notifications'
    | '/portal/profile'
    | '/portal/sama-naffa'
    | '/admin/'
    | '/portal/'
    | '/admin/ape-subscriptions/$id'
    | '/admin/kyc/$id'
    | '/admin/leads/abandoned'
    | '/admin/leads/pee'
    | '/admin/sponsor-codes/$id'
    | '/admin/transactions/$id'
    | '/admin/users/$id'
    | '/api/auth/$'
    | '/api/auth/check-availability'
    | '/api/auth/login'
    | '/api/auth/reset-password'
    | '/api/auth/send-otp'
    | '/api/auth/session'
    | '/api/auth/setup-password'
    | '/api/auth/sign-out'
    | '/api/auth/verify-and-create-account'
    | '/api/auth/verify-otp'
    | '/portal/sama-naffa/payment-failed'
    | '/portal/sama-naffa/payment-success'
    | '/admin/ape-subscriptions/'
    | '/admin/kyc/'
    | '/admin/notifications/'
    | '/admin/reconciliation/'
    | '/admin/settings/'
    | '/admin/sponsor-codes/'
    | '/admin/transactions/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ape'
    | '/apesenegal'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/pee'
    | '/register'
    | '/sama-naffa'
    | '/setup-password'
    | '/souscrire-ape'
    | '/admin'
    | '/admin/login'
    | '/ape/payment-status'
    | '/apesenegal/payment-failed'
    | '/apesenegal/payment-status'
    | '/apesenegal/payment-success'
    | '/portal/ape'
    | '/portal/compare'
    | '/portal/dashboard'
    | '/portal/notifications'
    | '/portal/profile'
    | '/portal/sama-naffa'
    | '/portal'
    | '/admin/ape-subscriptions/$id'
    | '/admin/kyc/$id'
    | '/admin/leads/abandoned'
    | '/admin/leads/pee'
    | '/admin/sponsor-codes/$id'
    | '/admin/transactions/$id'
    | '/admin/users/$id'
    | '/api/auth/$'
    | '/api/auth/check-availability'
    | '/api/auth/login'
    | '/api/auth/reset-password'
    | '/api/auth/send-otp'
    | '/api/auth/session'
    | '/api/auth/setup-password'
    | '/api/auth/sign-out'
    | '/api/auth/verify-and-create-account'
    | '/api/auth/verify-otp'
    | '/portal/sama-naffa/payment-failed'
    | '/portal/sama-naffa/payment-success'
    | '/admin/ape-subscriptions'
    | '/admin/kyc'
    | '/admin/notifications'
    | '/admin/reconciliation'
    | '/admin/settings'
    | '/admin/sponsor-codes'
    | '/admin/transactions'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/ape'
    | '/apesenegal'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/pee'
    | '/register'
    | '/sama-naffa'
    | '/setup-password'
    | '/souscrire-ape'
    | '/admin/_layout'
    | '/admin/login'
    | '/ape/payment-status'
    | '/apesenegal/payment-failed'
    | '/apesenegal/payment-status'
    | '/apesenegal/payment-success'
    | '/portal/ape'
    | '/portal/compare'
    | '/portal/dashboard'
    | '/portal/notifications'
    | '/portal/profile'
    | '/portal/sama-naffa'
    | '/admin/'
    | '/portal/'
    | '/admin/ape-subscriptions/$id'
    | '/admin/kyc/$id'
    | '/admin/leads/abandoned'
    | '/admin/leads/pee'
    | '/admin/sponsor-codes/$id'
    | '/admin/transactions/$id'
    | '/admin/users/$id'
    | '/api/auth/$'
    | '/api/auth/check-availability'
    | '/api/auth/login'
    | '/api/auth/reset-password'
    | '/api/auth/send-otp'
    | '/api/auth/session'
    | '/api/auth/setup-password'
    | '/api/auth/sign-out'
    | '/api/auth/verify-and-create-account'
    | '/api/auth/verify-otp'
    | '/portal/sama-naffa/payment-failed'
    | '/portal/sama-naffa/payment-success'
    | '/admin/ape-subscriptions/'
    | '/admin/kyc/'
    | '/admin/notifications/'
    | '/admin/reconciliation/'
    | '/admin/settings/'
    | '/admin/sponsor-codes/'
    | '/admin/transactions/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApeRoute: typeof ApeRouteWithChildren
  ApesenegalRoute: typeof ApesenegalRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PeeRoute: typeof PeeRoute
  RegisterRoute: typeof RegisterRoute
  SamaNaffaRoute: typeof SamaNaffaRoute
  SetupPasswordRoute: typeof SetupPasswordRoute
  SouscrireApeRoute: typeof SouscrireApeRoute
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminLoginRoute: typeof AdminLoginRoute
  PortalApeRoute: typeof PortalApeRoute
  PortalCompareRoute: typeof PortalCompareRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalNotificationsRoute: typeof PortalNotificationsRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalSamaNaffaRoute: typeof PortalSamaNaffaRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
  AdminApeSubscriptionsIdRoute: typeof AdminApeSubscriptionsIdRoute
  AdminKycIdRoute: typeof AdminKycIdRoute
  AdminLeadsAbandonedRoute: typeof AdminLeadsAbandonedRoute
  AdminLeadsPeeRoute: typeof AdminLeadsPeeRoute
  AdminSponsorCodesIdRoute: typeof AdminSponsorCodesIdRoute
  AdminTransactionsIdRoute: typeof AdminTransactionsIdRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthCheckAvailabilityRoute: typeof ApiAuthCheckAvailabilityRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthResetPasswordRoute: typeof ApiAuthResetPasswordRoute
  ApiAuthSendOtpRoute: typeof ApiAuthSendOtpRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthSetupPasswordRoute: typeof ApiAuthSetupPasswordRoute
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute
  ApiAuthVerifyAndCreateAccountRoute: typeof ApiAuthVerifyAndCreateAccountRoute
  ApiAuthVerifyOtpRoute: typeof ApiAuthVerifyOtpRoute
  AdminApeSubscriptionsIndexRoute: typeof AdminApeSubscriptionsIndexRoute
  AdminKycIndexRoute: typeof AdminKycIndexRoute
  AdminNotificationsIndexRoute: typeof AdminNotificationsIndexRoute
  AdminReconciliationIndexRoute: typeof AdminReconciliationIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminSponsorCodesIndexRoute: typeof AdminSponsorCodesIndexRoute
  AdminTransactionsIndexRoute: typeof AdminTransactionsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/souscrire-ape': {
      id: '/souscrire-ape'
      path: '/souscrire-ape'
      fullPath: '/souscrire-ape'
      preLoaderRoute: typeof SouscrireApeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-password': {
      id: '/setup-password'
      path: '/setup-password'
      fullPath: '/setup-password'
      preLoaderRoute: typeof SetupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sama-naffa': {
      id: '/sama-naffa'
      path: '/sama-naffa'
      fullPath: '/sama-naffa'
      preLoaderRoute: typeof SamaNaffaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pee': {
      id: '/pee'
      path: '/pee'
      fullPath: '/pee'
      preLoaderRoute: typeof PeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apesenegal': {
      id: '/apesenegal'
      path: '/apesenegal'
      fullPath: '/apesenegal'
      preLoaderRoute: typeof ApesenegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ape': {
      id: '/ape'
      path: '/ape'
      fullPath: '/ape'
      preLoaderRoute: typeof ApeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/sama-naffa': {
      id: '/portal/sama-naffa'
      path: '/portal/sama-naffa'
      fullPath: '/portal/sama-naffa'
      preLoaderRoute: typeof PortalSamaNaffaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/portal/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/notifications': {
      id: '/portal/notifications'
      path: '/portal/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof PortalNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/portal/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/compare': {
      id: '/portal/compare'
      path: '/portal/compare'
      fullPath: '/portal/compare'
      preLoaderRoute: typeof PortalCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/ape': {
      id: '/portal/ape'
      path: '/portal/ape'
      fullPath: '/portal/ape'
      preLoaderRoute: typeof PortalApeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apesenegal/payment-success': {
      id: '/apesenegal/payment-success'
      path: '/payment-success'
      fullPath: '/apesenegal/payment-success'
      preLoaderRoute: typeof ApesenegalPaymentSuccessRouteImport
      parentRoute: typeof ApesenegalRoute
    }
    '/apesenegal/payment-status': {
      id: '/apesenegal/payment-status'
      path: '/payment-status'
      fullPath: '/apesenegal/payment-status'
      preLoaderRoute: typeof ApesenegalPaymentStatusRouteImport
      parentRoute: typeof ApesenegalRoute
    }
    '/apesenegal/payment-failed': {
      id: '/apesenegal/payment-failed'
      path: '/payment-failed'
      fullPath: '/apesenegal/payment-failed'
      preLoaderRoute: typeof ApesenegalPaymentFailedRouteImport
      parentRoute: typeof ApesenegalRoute
    }
    '/ape/payment-status': {
      id: '/ape/payment-status'
      path: '/payment-status'
      fullPath: '/ape/payment-status'
      preLoaderRoute: typeof ApePaymentStatusRouteImport
      parentRoute: typeof ApeRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions/': {
      id: '/admin/transactions/'
      path: '/admin/transactions'
      fullPath: '/admin/transactions/'
      preLoaderRoute: typeof AdminTransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sponsor-codes/': {
      id: '/admin/sponsor-codes/'
      path: '/admin/sponsor-codes'
      fullPath: '/admin/sponsor-codes/'
      preLoaderRoute: typeof AdminSponsorCodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/admin/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reconciliation/': {
      id: '/admin/reconciliation/'
      path: '/admin/reconciliation'
      fullPath: '/admin/reconciliation/'
      preLoaderRoute: typeof AdminReconciliationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications/': {
      id: '/admin/notifications/'
      path: '/admin/notifications'
      fullPath: '/admin/notifications/'
      preLoaderRoute: typeof AdminNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kyc/': {
      id: '/admin/kyc/'
      path: '/admin/kyc'
      fullPath: '/admin/kyc/'
      preLoaderRoute: typeof AdminKycIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ape-subscriptions/': {
      id: '/admin/ape-subscriptions/'
      path: '/admin/ape-subscriptions'
      fullPath: '/admin/ape-subscriptions/'
      preLoaderRoute: typeof AdminApeSubscriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/sama-naffa/payment-success': {
      id: '/portal/sama-naffa/payment-success'
      path: '/payment-success'
      fullPath: '/portal/sama-naffa/payment-success'
      preLoaderRoute: typeof PortalSamaNaffaPaymentSuccessRouteImport
      parentRoute: typeof PortalSamaNaffaRoute
    }
    '/portal/sama-naffa/payment-failed': {
      id: '/portal/sama-naffa/payment-failed'
      path: '/payment-failed'
      fullPath: '/portal/sama-naffa/payment-failed'
      preLoaderRoute: typeof PortalSamaNaffaPaymentFailedRouteImport
      parentRoute: typeof PortalSamaNaffaRoute
    }
    '/api/auth/verify-otp': {
      id: '/api/auth/verify-otp'
      path: '/api/auth/verify-otp'
      fullPath: '/api/auth/verify-otp'
      preLoaderRoute: typeof ApiAuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify-and-create-account': {
      id: '/api/auth/verify-and-create-account'
      path: '/api/auth/verify-and-create-account'
      fullPath: '/api/auth/verify-and-create-account'
      preLoaderRoute: typeof ApiAuthVerifyAndCreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out'
      path: '/api/auth/sign-out'
      fullPath: '/api/auth/sign-out'
      preLoaderRoute: typeof ApiAuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/setup-password': {
      id: '/api/auth/setup-password'
      path: '/api/auth/setup-password'
      fullPath: '/api/auth/setup-password'
      preLoaderRoute: typeof ApiAuthSetupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/send-otp': {
      id: '/api/auth/send-otp'
      path: '/api/auth/send-otp'
      fullPath: '/api/auth/send-otp'
      preLoaderRoute: typeof ApiAuthSendOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reset-password': {
      id: '/api/auth/reset-password'
      path: '/api/auth/reset-password'
      fullPath: '/api/auth/reset-password'
      preLoaderRoute: typeof ApiAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/check-availability': {
      id: '/api/auth/check-availability'
      path: '/api/auth/check-availability'
      fullPath: '/api/auth/check-availability'
      preLoaderRoute: typeof ApiAuthCheckAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions/$id': {
      id: '/admin/transactions/$id'
      path: '/admin/transactions/$id'
      fullPath: '/admin/transactions/$id'
      preLoaderRoute: typeof AdminTransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sponsor-codes/$id': {
      id: '/admin/sponsor-codes/$id'
      path: '/admin/sponsor-codes/$id'
      fullPath: '/admin/sponsor-codes/$id'
      preLoaderRoute: typeof AdminSponsorCodesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads/pee': {
      id: '/admin/leads/pee'
      path: '/admin/leads/pee'
      fullPath: '/admin/leads/pee'
      preLoaderRoute: typeof AdminLeadsPeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads/abandoned': {
      id: '/admin/leads/abandoned'
      path: '/admin/leads/abandoned'
      fullPath: '/admin/leads/abandoned'
      preLoaderRoute: typeof AdminLeadsAbandonedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kyc/$id': {
      id: '/admin/kyc/$id'
      path: '/admin/kyc/$id'
      fullPath: '/admin/kyc/$id'
      preLoaderRoute: typeof AdminKycIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ape-subscriptions/$id': {
      id: '/admin/ape-subscriptions/$id'
      path: '/admin/ape-subscriptions/$id'
      fullPath: '/admin/ape-subscriptions/$id'
      preLoaderRoute: typeof AdminApeSubscriptionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApeRouteChildren {
  ApePaymentStatusRoute: typeof ApePaymentStatusRoute
}

const ApeRouteChildren: ApeRouteChildren = {
  ApePaymentStatusRoute: ApePaymentStatusRoute,
}

const ApeRouteWithChildren = ApeRoute._addFileChildren(ApeRouteChildren)

interface ApesenegalRouteChildren {
  ApesenegalPaymentFailedRoute: typeof ApesenegalPaymentFailedRoute
  ApesenegalPaymentStatusRoute: typeof ApesenegalPaymentStatusRoute
  ApesenegalPaymentSuccessRoute: typeof ApesenegalPaymentSuccessRoute
}

const ApesenegalRouteChildren: ApesenegalRouteChildren = {
  ApesenegalPaymentFailedRoute: ApesenegalPaymentFailedRoute,
  ApesenegalPaymentStatusRoute: ApesenegalPaymentStatusRoute,
  ApesenegalPaymentSuccessRoute: ApesenegalPaymentSuccessRoute,
}

const ApesenegalRouteWithChildren = ApesenegalRoute._addFileChildren(
  ApesenegalRouteChildren,
)

interface PortalSamaNaffaRouteChildren {
  PortalSamaNaffaPaymentFailedRoute: typeof PortalSamaNaffaPaymentFailedRoute
  PortalSamaNaffaPaymentSuccessRoute: typeof PortalSamaNaffaPaymentSuccessRoute
}

const PortalSamaNaffaRouteChildren: PortalSamaNaffaRouteChildren = {
  PortalSamaNaffaPaymentFailedRoute: PortalSamaNaffaPaymentFailedRoute,
  PortalSamaNaffaPaymentSuccessRoute: PortalSamaNaffaPaymentSuccessRoute,
}

const PortalSamaNaffaRouteWithChildren = PortalSamaNaffaRoute._addFileChildren(
  PortalSamaNaffaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApeRoute: ApeRouteWithChildren,
  ApesenegalRoute: ApesenegalRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  PeeRoute: PeeRoute,
  RegisterRoute: RegisterRoute,
  SamaNaffaRoute: SamaNaffaRoute,
  SetupPasswordRoute: SetupPasswordRoute,
  SouscrireApeRoute: SouscrireApeRoute,
  AdminLayoutRoute: AdminLayoutRoute,
  AdminLoginRoute: AdminLoginRoute,
  PortalApeRoute: PortalApeRoute,
  PortalCompareRoute: PortalCompareRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalNotificationsRoute: PortalNotificationsRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalSamaNaffaRoute: PortalSamaNaffaRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
  AdminApeSubscriptionsIdRoute: AdminApeSubscriptionsIdRoute,
  AdminKycIdRoute: AdminKycIdRoute,
  AdminLeadsAbandonedRoute: AdminLeadsAbandonedRoute,
  AdminLeadsPeeRoute: AdminLeadsPeeRoute,
  AdminSponsorCodesIdRoute: AdminSponsorCodesIdRoute,
  AdminTransactionsIdRoute: AdminTransactionsIdRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthCheckAvailabilityRoute: ApiAuthCheckAvailabilityRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthResetPasswordRoute: ApiAuthResetPasswordRoute,
  ApiAuthSendOtpRoute: ApiAuthSendOtpRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthSetupPasswordRoute: ApiAuthSetupPasswordRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
  ApiAuthVerifyAndCreateAccountRoute: ApiAuthVerifyAndCreateAccountRoute,
  ApiAuthVerifyOtpRoute: ApiAuthVerifyOtpRoute,
  AdminApeSubscriptionsIndexRoute: AdminApeSubscriptionsIndexRoute,
  AdminKycIndexRoute: AdminKycIndexRoute,
  AdminNotificationsIndexRoute: AdminNotificationsIndexRoute,
  AdminReconciliationIndexRoute: AdminReconciliationIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminSponsorCodesIndexRoute: AdminSponsorCodesIndexRoute,
  AdminTransactionsIndexRoute: AdminTransactionsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
