import type { LegalDocument } from './types';

/** Source: project_docs/CGU Sama Naffa 24062026 VF.docx */
export const CGU_TITLE = 'Conditions générales d\'utilisation';

export const CGU_VERSION = 'Sama Naffa — EVEREST Finance SA. Version 1.0, En vigueur à compter du 01/06/2026';

/** Excerpt shown in portal profile completion before full acceptance. */
export const CGU_ACCEPTANCE_SUMMARY: { heading: string; body: string }[] = [
  {
    heading: 'ARTICLE 2 - OBJET ET CHAMP D\'APPLICATION',
    body: 'Les présentes CGU ont pour objet de définir les conditions dans lesquelles EVEREST Finance met à disposition de ses Clients Sama Naffa, plateforme digitale donnant accès au Marché Financier Régional et Marché des Titres Publics, destinée aux particuliers résidant au Sénégal. Sama Naffa permet au Client de constituer une épargne en FCFA, investie par EVEREST Finance pour le compte individuel de chaque Client, sur la base d’un mandat de gestion écrit, en titres souverains émis par les États membre',
  },
  {
    heading: 'ARTICLE 4 - CONDITIONS D\'ÉLIGIBILITÉ ET PROCÉDURE D\'INSCRIPTION',
    body: 'Pour accéder à Sama Naffa, le Client doit remplir cumulativement les conditions suivantes : L\'inscription à Sama Naffa s\'effectue exclusivement via l\'Application selon les étapes suivantes : EVEREST Finance se réserve le droit de demander tout document complémentaire nécessaire à la vérification d\'identité, à l\'évaluation du profil de risque ou à la conformité LBC/FT. L\'ouverture du Compte Client n\'est définitive qu\'après validation par EVEREST Finance du dossier KYC complet. Les Clients identif',
  },
  {
    heading: 'ARTICLE 5 - DESCRIPTION DE SAMA NAFFA',
    body: 'Sama Naffa est un service de gestion de portefeuille sous mandat proposé par EVEREST Finance, SGI agréée par l\'AMF-UMOA. Dans le cadre de ce service, le Client confie à EVEREST Finance un mandat de gestion en vertu duquel celle-ci souscrit, pour le compte exclusif et individualisé du Client, à des titres souverains émis par les États membres de l\'UEMOA et négociés sur le Marché Financier Régional. Le compte ouvert au nom du Client est un compte-titres individuel. Les titres y sont inscrits nomin',
  },
  {
    heading: 'ARTICLE 10 - RETRAIT ANTICIPÉ ET CONSÉQUENCES',
    body: 'Constitue un Retrait Anticipé tout retrait de fonds effectué par le Client avant l\'échéance de sa Date Anniversaire contractuelle. En cas de Retrait Anticipé, le Client reconnaît expressément et accepte que : Les gains (produits de la gestion) accumulés depuis le dernier Versement ou depuis la dernière Date Anniversaire peuvent être partiellement ou totalement perdus, selon les conditions de marché au jour du retrait EVEREST Finance procédera à la liquidation de la position du Client sur le Marc',
  },
  {
    heading: 'ARTICLE 12 - OBJECTIFS DE RENDEMENT ET RISQUES',
    body: 'EVEREST Finance communique les objectifs de rendement à titre indicatif et non contractuel. Ces objectifs sont fondés sur les performances historiques observées sur le Marché Financier Régional de l\'UEMOA et sur l\'expertise de gestion de EVEREST Finance. Ils ne constituent pas une promesse de rendement. Le Client est informé des principaux risques inhérents au Sama Naffa : Risque de marché : les performances effectivement réalisées peuvent différer des objectifs en raison des fluctuations du Mar',
  },
  {
    heading: 'ARTICLE 20 - DROIT APPLICABLE ET JURIDICTION',
    body: 'Les présentes CGU sont soumises et interprétées conformément au droit sénégalais, aux réglementations de l\'AMF-UMOA et de la BCEAO applicables. En cas de litige relatif à l\'interprétation ou à l\'exécution des présentes CGU, et après tentative de résolution amiable, les parties conviennent de soumettre leur différend aux juridictions compétentes de Dakar, Sénégal. Préalablement à tout recours judiciaire, les parties s\'engagent à tenter de résoudre leur différend à l\'amiable dans un délai de soixa',
  },
  {
    heading: 'ARTICLE 21 - DISPOSITIONS FINALES',
    body: 'Les présentes CGU, ensemble avec la Grille Tarifaire, le mandat de gestion et la Politique de Protection des Données Personnelles, constituent l\'intégralité de l\'accord entre EVEREST Finance et le Client concernant Sama Naffa. Si l\'une des dispositions des présentes CGU s\'avère nulle ou inapplicable au regard d\'une règle de droit en vigueur, elle sera réputée non écrite. Les autres dispositions demeureront pleinement en vigueur.',
  },
];

export const CGU: LegalDocument = {
  title: CGU_TITLE,
  subtitle: 'Sama Naffa — EVEREST Finance SA. Version 1.0, En vigueur à compter du 01/06/2026',
  sections: [
    { type: 'paragraph', text: 'EVEREST Finance SA — Société de Gestion et d\'Intermédiation — Agrément AMF-UMOA n° SGI/2016-01 — RCCM : SN DKR 2023 M 5240 — NINEA : 005660536 2A3 — Siège social — Immeuble Platinum, 4ème étage — 18, Boulevard de la République — Dakar, Sénégal, BP : 11659 — Tél. : +221 33 822 87 00 — contact@everestfin.com' },
    { type: 'heading', text: 'ARTICLE 1 - DÉFINITIONS' },
    { type: 'paragraph', text: 'Aux fins des présentes Conditions Générales d\'Utilisation, les termes définis ci-dessous ont la signification suivante : AMF-UMOA : Autorité des Marchés Financiers de l\'Union Monétaire Ouest Africaine (anciennement CREPMF), organe de régulation du marché financier régional de l\'UEMOA. Application : La plateforme digitale Sama Naffa, accessible via navigateur mobile ou application, permettant au Client d’accéder au service de gestion sous mandat Sama Naffa et de suivre son portefeuille. BCEAO : Banque Centrale des États de l\'Afrique de l\'Ouest, autorité monétaire de la zone UEMOA. CGU : Les présentes Conditions Générales d\'Utilisation, constituant le contrat liant EVEREST Finance au Client. Client : Toute personne physique majeure, résidant au Sénégal, ayant adhéré au service Sama Naffa après acceptation des présentes CGU et validation de son dossier KYC. Compte Client : Espace personnel et sécurisé ouvert au nom du Client sur l\'Application, donnant accès à ses informations d\'épargne, à ses relevés et à ses opérations. Date Anniversaire : Date correspondant à l’anniversaire annuel du premier versement effectif réalisé par le Client, servant de date de référence pour la mise à disposition de la valorisation de son portefeuille. Le capital n’est pas garanti. Versement : Toute somme versée par le Client sur son Compte Client via les Moyens de Paiement disponibles sur l’Application, destinée à être investie en titres pour son compte. EVEREST Finance : EVEREST Finance SA, Société de Gestion et d\'Intermédiation agréée par l\'AMF-UMOA sous le numéro SGI/2016-01, société anonyme au capital de 1 000 000 000 FCFA, dont le siège est à Dakar, Sénégal. Grille Tarifaire : Grille de tarification des services d\'EVEREST Finance homologuée par l\'AMF-UMOA, disponible sur l\'Application et pouvant être modifiée sous réserve de notification préalable au Client. Intouch / Agrégateur : InTouch Group, prestataire de services de paiement agréé par la BCEAO, assurant l\'agrégation et le traitement des paiements effectués via les wallets mobiles (Orange Money, Wave, Free Money et autres). KYC : Procédure de connaissance client (Know Your Customer) conforme aux exigences de l\'AMF-UMOA et aux obligations LBC/FT, comprenant la vérification d\'identité et l\'évaluation du profil d\'investisseur du Client. LBC/FT : Lutte contre le Blanchiment de Capitaux et le Financement du Terrorisme, conformément à la Directive n°02/2015/CM/UEMOA et aux législations nationales applicables. Marché Financier Régional (MFR) : Marché financier de l\'UEMOA organisé autour de la BRVM (Bourse Régionale des Valeurs Mobilières) et d\'UMOA-Titres, régulé par l\'AMF-UMOA. Moyen de Paiement : Tout instrument de paiement mobile agréé disponible sur l\'Application (Orange Money, Wave, Free Money et tout autre moyen agréé par la BCEAO), traité par le biais de l\'Agrégateur. Objectif de Rendement / Rendement Escompté : Taux de rendement indicatif et non garanti, communiqué à titre d\'objectif de performance par EVEREST Finance, basé sur les conditions de marché observées sur le Marché Financier Régional. Ce taux ne constitue pas un engagement contractuel. Profil d\'Investisseur : Évaluation de la situation financière, des objectifs d\'investissement et de la tolérance au risque du Client, réalisée conformément à l\'Instruction N°60/CREPMF/2020. Retrait Anticipé : Tout retrait effectué par le Client avant la Date Anniversaire applicable à sa Formule. Sama Naffa : Service de gestion sous mandat proposé par EVEREST Finance via l’Application, permettant à chaque Client de constituer, pour son compte exclusif et individualisé, un portefeuille de titres souverains émis par les États membres de l’UEMOA et négociés sur le Marché Financier Régional. UEMOA : Union Économique et Monétaire Ouest Africaine, regroupant huit (8) États membres : Bénin, Burkina Faso, Côte d\'Ivoire, Guinée-Bissau, Mali, Niger, Sénégal, Togo.' },
    { type: 'heading', text: 'ARTICLE 2 - OBJET ET CHAMP D\'APPLICATION' },
    { type: 'heading', text: '2.1 Objet' },
    { type: 'paragraph', text: 'Les présentes CGU ont pour objet de définir les conditions dans lesquelles EVEREST Finance met à disposition de ses Clients Sama Naffa, plateforme digitale donnant accès au Marché Financier Régional et Marché des Titres Publics, destinée aux particuliers résidant au Sénégal. Sama Naffa permet au Client de constituer une épargne en FCFA, investie par EVEREST Finance pour le compte individuel de chaque Client, sur la base d’un mandat de gestion écrit, en titres souverains émis par les États membres de l’UEMOA et négociés sur le Marché Financier Régional.' },
    { type: 'heading', text: '2.2 Acceptation des CGU' },
    { type: 'paragraph', text: 'L\'utilisation de Sama Naffa est subordonnée à l\'acceptation expresse des présentes CGU. En cliquant sur "J\'accepte les Conditions Générales d\'Utilisation" lors de l\'inscription, le Client reconnaît avoir lu, compris et accepté sans réserve l\'intégralité des présentes CGU. Les CGU sont également acceptées à chaque Versement ou opération réalisée via la plateforme.' },
    { type: 'heading', text: '2.3 Documents contractuels' },
    { type: 'paragraph', text: 'Outre les présentes CGU, la relation contractuelle entre EVEREST Finance et le Client est régie par les documents suivants :' },
    {
      type: 'list',
      items: [
        'Le mandat de gestion (convention de gestion sous mandat)',
        "La Grille Tarifaire homologuée par l'AMF-UMOA",
        "Le Formulaire d'adhésion et de Profil d'Investisseur (KYC)",
        'La Politique de Protection des Données Personnelles',
        'Toute communication contractuelle spécifique adressée au Client',
      ],
    },
    { type: 'heading', text: 'ARTICLE 3 - CADRE RÉGLEMENTAIRE APPLICABLE' },
    { type: 'paragraph', text: 'Sama Naffa est régi et soumis au respect des textes réglementaires suivants, sans que cette liste soit limitative :' },
    { type: 'heading', text: '3.1 Réglementation des marchés financiers' },
    { type: 'paragraph', text: 'Règlement Général de l\'AMF-UMOA relatif à l\'organisation et au fonctionnement du Marché Financier Régional de l\'UEMOA Instruction N°60/CREPMF/2020 relative à l\'activité de gestion sous mandat sur le Marché Financier Régional Instruction N°61/CREPMF/2020 relative au contrôle interne des acteurs du Marché Financier Régional Instruction N°62/CREPMF/2020 relative au cantonnement des fonds de la clientèle des sociétés de gestion et d’intermédiation Instruction N°68/CREPMF/2021 relative à la tenue des comptes-titres et espèces auprès des teneurs de comptes Convention portant création de l\'AMF-UMOA du 3 juillet 1996 et son avenant du 3 juillet 1997' },
    { type: 'heading', text: '3.2 Réglementation des paiements et de la monnaie électronique' },
    { type: 'paragraph', text: 'Instruction N°001-01-2024 de la BCEAO relative aux conditions et modalités de fourniture de services de paiement dans les États membres de l\'UMOA (entrée en vigueur le 23 janvier 2024) Règlement N°15/2002/CM/UEMOA du 19 septembre 2002 relatif aux systèmes de paiement dans les États membres de l\'UEMOA Instruction N°008-05-2015 de la BCEAO régissant les conditions et modalités d\'exercice des activités des émetteurs de monnaie électronique dans l\'UMOA Décision N°31 du 29 septembre 2015 relative à la compensation et au règlement des opérations monétiques dans l\'UMOA' },
    { type: 'heading', text: '3.3 Lutte contre le blanchiment et financement du terrorisme' },
    { type: 'paragraph', text: 'Directive N°02/2015/CM/UEMOA relative à la lutte contre le blanchiment de capitaux et le financement du terrorisme dans les États membres de l\'UEMOA Loi sénégalaise N°2004-09 du 6 février 2004 relative au blanchiment de capitaux et ses textes d\'application Recommandations du GAFI (Groupe d\'Action Financière) applicables aux institutions financières' },
    { type: 'heading', text: '3.4 Protection des données personnelles' },
    { type: 'paragraph', text: 'Loi sénégalaise N°2008-12 du 25 janvier 2008 sur la Protection des Données à Caractère Personnel Règlements et décisions de la Commission de Protection des Données Personnelles (CDP) du Sénégal' },
    { type: 'heading', text: '3.5 Droit des sociétés et des obligations' },
    { type: 'paragraph', text: 'Acte Uniforme OHADA relatif au Droit des Sociétés Commerciales et du Groupement d\'Intérêt Économique Code des Obligations Civiles et Commerciales (COCC) de la République du Sénégal Loi sénégalaise sur les transactions électroniques' },
    { type: 'heading', text: 'ARTICLE 4 - CONDITIONS D\'ÉLIGIBILITÉ ET PROCÉDURE D\'INSCRIPTION' },
    { type: 'heading', text: '4.1 Conditions d\'éligibilité' },
    { type: 'paragraph', text: 'Pour accéder à Sama Naffa, le Client doit remplir cumulativement les conditions suivantes :' },
    {
      type: 'list',
      items: [
        'Être une personne physique âgée d\'au moins 18 ans révolus ;',
        'Résider au Sénégal et justifier de cette résidence par la production d\'un justificatif de domicile de moins de trois (3) mois (facture d\'eau, d\'électricité, de téléphone fixe, attestation bancaire ou titre de location) ou, à défaut, par la production d\'une Carte Nationale d\'Identité sénégalaise en cours de validité ;',
        'Disposer d\'un numéro de téléphone mobile actif détenu auprès d\'un opérateur sénégalais ;',
        'Disposer d\'une adresse email valide et active ;',
        'Disposer d\'un compte de monnaie électronique actif auprès d\'un opérateur partenaire (Orange Money, Wave, Free Money ou tout autre opérateur agréé) ;',
        'Fournir une pièce d\'identité officielle valide (Carte Nationale d\'Identité sénégalaise, passeport ou titre de séjour en cours de validité) ;',
        'Ne pas être frappé d\'une incapacité juridique ou d\'une mesure de protection judiciaire ;',
        'Ne pas être soumis à des sanctions ou mesures restrictives émises par les autorités compétentes ;',
        'Ne pas être identifié comme Personne Politiquement Exposée (PPE) sans avoir satisfait aux mesures de vigilance renforcée prévues à l\'Article 14.',
      ],
    },
    { type: 'heading', text: '4.2 Procédure d\'inscription et KYC' },
    { type: 'paragraph', text: 'L\'inscription à Sama Naffa s\'effectue exclusivement via l\'Application selon les étapes suivantes :' },
    {
      type: 'list',
      items: [
        'Saisie du numéro de téléphone mobile et validation par code OTP (One Time Password) ;',
        'Renseignement des informations personnelles (nom, prénom, date et lieu de naissance, nationalité, adresse de résidence) ;',
        'Déclaration de la profession, de l\'employeur le cas échéant, et indication de l\'origine des fonds (exigences LBC/FT) ;',
        'Déclaration éventuelle de qualité de Personne Politiquement Exposée (PPE) ou d\'apparenté de PPE au sens de la Directive N°02/2015/CM/UEMOA ;',
        'Téléversement d\'une copie lisible d\'une pièce d\'identité officielle en cours de validité (recto et verso) ;',
        'Téléversement d\'un justificatif de domicile de moins de trois (3) mois ;',
        'Réalisation d\'une vérification d\'identité par capture vidéo en direct (liveness check) destinée à confirmer que le Client est bien la personne titulaire de la pièce d\'identité fournie ;',
        'Acceptation des présentes CGU et de la Politique de Protection des Données Personnelles ;',
        'Complétion du questionnaire de Profil d\'Investisseur conformément à l\'Instruction N°60/CREPMF/2020.',
      ],
    },
    { type: 'paragraph', text: 'EVEREST Finance se réserve le droit de demander tout document complémentaire nécessaire à la vérification d\'identité, à l\'évaluation du profil de risque ou à la conformité LBC/FT. L\'ouverture du Compte Client n\'est définitive qu\'après validation par EVEREST Finance du dossier KYC complet. Les Clients identifiés comme PPE sont soumis aux mesures de vigilance renforcée prévues à l\'Article 14.' },
    { type: 'heading', text: '4.3 Dossier KYC incomplet ou non conforme' },
    { type: 'paragraph', text: 'En cas de dossier KYC incomplet, EVEREST Finance notifie le Client par voie électronique ou SMS des pièces manquantes. Le Client dispose d\'un délai de trente (30) jours calendaires pour compléter son dossier. Passé ce délai, le dossier est clôturé et les éventuels fonds déjà versés sont restitués au Client. EVEREST Finance se réserve le droit de suspendre ou clôturer un Compte Client dont le dossier KYC s\'avère postérieurement non conforme, frauduleux ou incomplet.' },
    { type: 'heading', text: 'ARTICLE 5 - DESCRIPTION DE SAMA NAFFA' },
    { type: 'heading', text: '5.1 Nature du service' },
    { type: 'paragraph', text: 'Sama Naffa est un service de gestion de portefeuille sous mandat proposé par EVEREST Finance, SGI agréée par l\'AMF-UMOA. Dans le cadre de ce service, le Client confie à EVEREST Finance un mandat de gestion en vertu duquel celle-ci souscrit, pour le compte exclusif et individualisé du Client, à des titres souverains émis par les États membres de l\'UEMOA et négociés sur le Marché Financier Régional. Le compte ouvert au nom du Client est un compte-titres individuel. Les titres y sont inscrits nominativement et ne sont à aucun moment confondus avec les actifs propres d\'EVEREST Finance ni avec ceux d\'autres Clients. Le Client conserve à tout moment la pleine propriété des titres acquis pour son compte. Le Sama Naffa ne constitue ni un compte bancaire, ni un compte de dépôt à vue, ni un produit d\'assurance, ni un Organisme de Placement Collectif en Valeurs Mobilières (OPCVM). Cantonnement et individualisation. Les sommes versées en attente d’investissement sont logées sur un compte de la clientèle distinct des fonds propres d’EVEREST Finance, conformément à l’Instruction N°62/CREPMF/2020. Les titres acquis sont inscrits au nom du Client, conformément à l’Instruction N°68/CREPMF/2021. Mandat écrit et signature électronique. La gestion est exercée sur la base d’un mandat de gestion écrit, accepté par le Client au moyen d’une signature électronique reposant sur un certificat délivré par un organisme agréé, conformément à la loi n°2008-08 du 25 janvier 2008 et à l’article 8 de l’Instruction N°60/CREPMF/2020.' },
    { type: 'heading', text: '5.2 Horizon de Placement' },
    { type: 'paragraph', text: 'EVEREST Finance applique un principe fondamental en gestion de placements : le rendement escompté est directement lié à l’horizon de placement du Client. Plus l’horizon de placement est long, plus l’objectif de rendement communiqué est élevé, en raison des opportunités d’investissement accessibles sur des durées plus longues et des meilleures conditions de liquidité offertes à EVEREST Finance pour optimiser l’allocation des actifs.' },
    { type: 'heading', text: '5.2.1 - Principe du lien horizon-rendement' },
    { type: 'paragraph', text: 'Sur le Marché Financier Régional de l’UEMOA, les instruments à échéance plus longue offrent structurellement des rendements supérieurs aux instruments court terme. Ce phénomène, connu sous le nom de prime de liquidité, rémunère l’investisseur pour son acceptation d’immobiliser ses fonds sur une durée plus étendue.' },
    { type: 'heading', text: '5.2.2 - Fonctionnement pratique' },
    { type: 'paragraph', text: 'Le Client choisit librement son horizon de placement à l’ouverture de son Compte Client. L’horizon retenu détermine l’objectif de rendement applicable à ce Versement. Le Client ne peut plus modifier son horizon de placement pour les Versements futurs sur un compte titre déjà ouvert. Lorsque le Client opte pour un horizon long (36 mois et plus), la Date Anniversaire constitue la date contractuelle à partir de laquelle l’objectif de rendement majoré s’applique dans sa totalité. Un retrait antérieur à cette date est qualifié de Retrait Anticipé et peut entraîner une réduction ou une perte des gains accumulés, conformément à l’Article 10 des présentes CGU.' },
    { type: 'heading', text: '5.2.3 - Objectifs de rendement applicables' },
    { type: 'paragraph', text: 'Le tableau ci-dessous présente les objectifs de rendement bruts escomptés selon l\'horizon de placement retenu. Ces objectifs sont établis par EVEREST Finance sur la base d\'une méthodologie de backtest documentée, fondée sur les rendements historiques observés sur les titres souverains émis par les États membres de l\'UEMOA et négociés sur le Marché Financier Régional, sur une période de référence d\'au moins cinq (5) années glissantes. Cette méthodologie est tenue à la disposition du Client sur demande adressée à samanaffa@everestfin.com. Ces objectifs sont donnés à titre purement indicatif et ne constituent en aucun cas des taux contractuels garantis, conformément aux dispositions de l\'Article 5.3. Les rendements bruts affichés s\'entendent avant prélèvement des frais de gestion et des frais de valorisation visés à l\'Article 11, ainsi que des éventuelles commissions réglementaires reversées aux organismes de marché (AMF-UMOA, DC/BR, BRVM). Le rendement effectivement perçu par le Client peut donc être sensiblement inférieur au rendement brut affiché. Court terme (12 mois) : objectif de 4,5% brut/an* Court à moyen terme (24 à 36 mois) : objectif de 6,0% brut/an* Moyen à long terme (36 à 60 mois) : objectif de 7,0% brut/an* Très long terme (60 à 240 mois) : objectif de 8,0% brut/an* * Objectifs de performance non garantis. Les résultats réels dépendent des conditions du Marché Financier Régional de l\'UEMOA, de l\'évolution des taux d\'intérêt et de la solvabilité des émetteurs souverains. Voir Article 5.3 et Article 12' },
    { type: 'heading', text: '5.2.4 - Neutralité du choix d’horizon' },
    { type: 'paragraph', text: 'Le choix de l’horizon de placement appartient exclusivement au Client, en fonction de ses objectifs personnels, de sa situation financière et de sa capacité à immobiliser des fonds. EVEREST Finance ne formule aucune recommandation d’investissement à ce titre. Le Client est informé que :' },
    {
      type: 'list',
      items: [
        'Un horizon court n’est pas inférieur à un horizon long ; il correspond simplement à un besoin de liquidité plus élevé, légitime et respecté par EVEREST Finance.',
        'Un horizon long n’est recommandable que si le Client dispose d’une capacité réelle à ne pas mobiliser les fonds concernés pendant la durée d’engagement, au risque de supporter les conséquences d’un Retrait Anticipé décrit à l’Article 10.',
      ],
    },
    { type: 'heading', text: '5.3 Caractère non garanti des rendements' },
    { type: 'paragraph', text: 'Les rendements présentés dans le cadre de Sama Naffa sont des objectifs de performance et non des taux contractuels garantis. EVEREST Finance ne saurait être tenue responsable d\'un rendement effectif inférieur à l\'objectif communiqué, dans la mesure où celui-ci dépend des conditions de Marché. Les performances passées ne constituent pas un indicateur fiable des résultats futurs. Le Client reconnaît avoir été informé de ce caractère non garanti avant toute adhésion.' },
    { type: 'heading', text: 'ARTICLE 6 - MODALITÉS DE VERSEMENT ET MOYENS DE PAIEMENT' },
    { type: 'heading', text: '6.1 Moyens de paiement acceptés' },
    { type: 'paragraph', text: 'Les Versements sont effectués exclusivement via les Moyens de Paiement digitaux agréés disponibles sur l\'Application et les réseaux physiques affiliés, traités par l\'Agrégateur InTouch Group (ou tout autre agrégateur de paiements agréé par la BCEAO que EVEREST Finance serait amenée à substituer), notamment : Orange Money Wave Free Money Tout autre portefeuille électronique agréé par la BCEAO disponible sur l\'Application Versement en espèces auprès d\'un réseau physique affilié, crédité sur le Compte Client' },
    { type: 'heading', text: '6.2 Frais de versement' },
    { type: 'paragraph', text: 'EVEREST Finance supporte les frais afférents aux Versements effectués par le Client. Les éventuels frais de transaction prélevés par l\'opérateur de monnaie électronique ou l\'Agrégateur sont à la charge exclusive du Client et sont distinctement indiqués lors de chaque opération.' },
    { type: 'heading', text: '6.3 Traitement des versements' },
    { type: 'paragraph', text: 'Tout Versement est crédité sur le Compte Client dans un délai maximum de vingt-quatre (24) heures ouvrables à compter de la confirmation de paiement par l\'Agrégateur. EVEREST Finance ne peut être tenue responsable de retards imputables aux opérateurs de monnaie électronique ou à l\'Agrégateur. Chaque Versement fait l\'objet d\'une confirmation par notification push et/ou SMS adressée au numéro de téléphone enregistré du Client.' },
    { type: 'heading', text: '6.4 Montant minimum de versement' },
    { type: 'paragraph', text: 'Le montant minimum pour l\'ouverture d\'un Compte Client est fixé à mille (1 000) FCFA et ses multiples. Les versements ultérieurs sont soumis à la même règle de multiple, dans la limite des plafonds fixés par la réglementation applicable et les capacités techniques de l\'Application.' },
    { type: 'heading', text: '6.5 Opérations suspectes' },
    { type: 'paragraph', text: 'En application des obligations LBC/FT, EVEREST Finance se réserve le droit de bloquer, suspendre ou signaler aux autorités compétentes tout Versement paraissant d\'une origine douteuse, incohérente avec le profil déclaré du Client, ou susceptible de constituer une opération de blanchiment de capitaux ou de financement du terrorisme.' },
    { type: 'heading', text: 'ARTICLE 7 - FONCTIONNEMENT DU COMPTE CLIENT' },
    { type: 'heading', text: '7.1 Accès au Compte Client' },
    { type: 'paragraph', text: 'Le Client accède à son Compte Client via l\'Application, en s\'authentifiant par son numéro de téléphone et son code PIN ou par validation biométrique si son appareil le permet. Il est seul responsable de la confidentialité de ses identifiants d\'accès.' },
    { type: 'heading', text: '7.2 Tableau de bord' },
    { type: 'paragraph', text: 'Le Compte Client donne accès à un tableau de bord présentant : Le solde d\'épargne en temps réel L\'historique de tous les Versements et Retraits La projection indicative des rendements escomptés à la prochaine Date Anniversaire Les relevés de compte téléchargeables La Date Anniversaire applicable Les projections de rendement affichées dans le tableau de bord sont indicatives et fondées sur l\'objectif de performance en cours. Elles ne constituent pas un engagement contractuel d\'EVEREST Finance.' },
    { type: 'heading', text: '7.3 Relevés de compte' },
    { type: 'paragraph', text: 'Un relevé de compte est disponible sur l\'Application à tout moment. Un relevé périodique est automatiquement disponible à chaque Date Anniversaire et à chaque opération significative.' },
    { type: 'heading', text: '7.4 Unicité du compte' },
    { type: 'paragraph', text: 'Un Client ne peut détenir qu\'un (1) seul Compte Client actif sur la plateforme Sama Naffa. La création de comptes multiples par une même personne sous des identités distinctes est strictement prohibée et constitue une infraction passible de clôture immédiate de l\'ensemble des comptes concernés. Au sein de son Compte Client unique, le Client est autorisé à ouvrir un nombre illimité de sous-comptes. Chaque sous-compte correspond à un objectif d\'épargne individualisé, maison, études, voyage, retraite, business ou tout autre objectif librement défini par le Client, assorti d\'un horizon de placement et d\'un objectif de rendement escompté propres, déterminés conformément à l\'Article 5.2 des présentes CGU. Les sous-comptes fonctionnent de manière indépendante au sein du Compte Client : les versements, les horizons de placement et les conditions de retrait sont gérés séparément pour chaque sous-compte. Le Client peut à tout moment créer, alimenter ou clôturer un sous-compte sans que cela n\'affecte les autres sous-comptes ni le Compte Client principal. La clôture d’un sous-compte avant l’échéance de son horizon de placement est assimilée à un Retrait Anticipé au sens de l’Article 10. Le Client reçoit la valeur de liquidation de son portefeuille au prix de marché à la date de clôture, laquelle peut être inférieure aux sommes versées, le capital n’étant pas garanti.' },
    { type: 'heading', text: 'ARTICLE 8 - DATE ANNIVERSAIRE ET MISE À DISPOSITION DES SOMMES' },
    { type: 'heading', text: '8.1 Principe de la Date Anniversaire' },
    { type: 'paragraph', text: 'La Date Anniversaire constitue la date de référence à partir de laquelle le Client peut demander la mise à disposition de la valeur de liquidation de son portefeuille, soit les sommes versées augmentées ou diminuées de la performance réelle des titres détenus pour son compte. Le capital n’est pas garanti. La Date Anniversaire est calculée à partir de la date du premier Versement effectif validé sur le Compte Client, et se reproduit chaque année ou toutes les fins de période prédéfinie selon l’horizon de placement choisi.' },
    { type: 'heading', text: '8.2 Mise à disposition des sommes à la Date Anniversaire' },
    { type: 'paragraph', text: 'À la Date Anniversaire, le Client peut demander la mise à disposition, totale ou partielle, de la valorisation de son portefeuille, sans frais de sortie. Le montant mis à disposition correspond à la valeur de liquidation des titres au prix de marché. Le remboursement à la Date Anniversaire est effectué dans un délai maximum de cinq (5) jours ouvrés suivant la demande, par versement sur le Moyen de Paiement désigné par le Client.' },
    { type: 'heading', text: '8.3 Reconduction automatique' },
    { type: 'paragraph', text: 'À l\'approche de la Date Anniversaire, le Client dispose d\'une fenêtre de décision de soixante (60) jours, ouverte trente (30) jours avant la Date Anniversaire et clôturée trente (30) jours après celle-ci, pendant laquelle il peut, à son choix :' },
    {
      type: 'list',
      items: [
        'demander le retrait total ou partiel de la valeur de liquidation de son portefeuille ;',
        'maintenir son placement à l\'identique pour une nouvelle période ;',
        'modifier les paramètres de son sous-compte (horizon, montant) sous réserve des conditions applicables.',
      ],
    },
    { type: 'paragraph', text: 'Pendant cette fenêtre de décision, les sommes restent investies aux conditions de l’horizon échu et le portefeuille continue d’évoluer selon la performance réelle des titres détenus pour le compte du Client. À l\'issue de la fenêtre de décision et en l\'absence d\'action expresse du Client, l\'horizon de placement est automatiquement reconduit pour une nouvelle période identique, aux conditions tarifaires et d\'objectif de rendement en vigueur à la date de reconduction. Le Client est informé de la reconduction automatique imminente par notification push, SMS et email, au moins trente (30) jours avant la Date Anniversaire, puis à nouveau cinq (5) jours avant la clôture de la fenêtre de décision.' },
    { type: 'heading', text: 'ARTICLE 9 - CONDITIONS DE RETRAIT' },
    { type: 'heading', text: '9.1 Retrait à l\'échéance normale' },
    { type: 'paragraph', text: 'Le Client perçoit la valeur de liquidation de son portefeuille au prix de marché, soit les sommes versées augmentées ou diminuées de la performance réelle des titres détenus pour son compte. Le capital n’est pas garanti et l’objectif de rendement ne constitue pas un engagement contractuel.' },
    { type: 'heading', text: '9.2 Demande de retrait - Procédure' },
    { type: 'paragraph', text: 'Le retrait est initié exclusivement via l\'Application. Le Client sélectionne le montant du retrait souhaité et valide l\'opération par son code PIN ou sa validation biométrique. Chaque demande de retrait fait l\'objet d\'une confirmation par OTP envoyé au numéro de téléphone enregistré. Les fonds sont versés sur le Moyen de Paiement principal enregistré dans le Compte Client. EVEREST Finance ne procède pas à des remboursements en espèces.' },
    { type: 'heading', text: '9.3 Délais de traitement' },
    { type: 'paragraph', text: 'Les retraits programmés à la Date Anniversaire sont traités dans un délai maximum de cinq (5) jours ouvrés à compter de la demande du Client, sous réserve des conditions de liquidité du marché. Ce délai est aligné sur celui prévu à l\'Article 8.2. EVEREST Finance s\'efforce de procéder au versement effectif des fonds dans les meilleurs délais et informe le Client par notification de l\'exécution effective du retrait.' },
    { type: 'heading', text: '9.4 Plafonds de retrait' },
    { type: 'paragraph', text: 'Des plafonds journaliers et mensuels de retrait peuvent s\'appliquer conformément à la réglementation BCEAO sur les services de paiement (Instruction N°001-01-2024) et aux capacités de l\'Agrégateur. Ces plafonds sont indiqués dans l\'Application et peuvent évoluer sous notification préalable.' },
    { type: 'heading', text: 'ARTICLE 10 - RETRAIT ANTICIPÉ ET CONSÉQUENCES' },
    { type: 'heading', text: '10.1 Définition du retrait anticipé' },
    { type: 'paragraph', text: 'Constitue un Retrait Anticipé tout retrait de fonds effectué par le Client avant l\'échéance de sa Date Anniversaire contractuelle.' },
    { type: 'heading', text: '10.2 Conséquences sur les gains' },
    { type: 'paragraph', text: 'En cas de Retrait Anticipé, le Client reconnaît expressément et accepte que : Les gains (produits de la gestion) accumulés depuis le dernier Versement ou depuis la dernière Date Anniversaire peuvent être partiellement ou totalement perdus, selon les conditions de marché au jour du retrait EVEREST Finance procédera à la liquidation de la position du Client sur le Marché Financier Régional aux conditions de marché du jour du retrait, lesquelles peuvent être inférieures à la valeur nominale des actifs détenus L\'objectif de rendement escompté est calculé sur la durée complète de l\'engagement ; un retrait avant terme ne donne pas droit au prorata des gains Des frais peuvent s\'appliquer conformément à la Grille Tarifaire homologuée par l\'AMF-UMOA' },
    { type: 'heading', text: '10.3 Liquidation et capital non garanti' },
    { type: 'paragraph', text: 'En cas de Retrait Anticipé, EVEREST Finance procède à la liquidation de la position du Client sur le Marché Financier Régional. Le Client perçoit le produit de cette liquidation, déduction faite des frais de cession ou de liquidation de position applicables selon la Grille Tarifaire homologuée. Le capital versé n\'est pas garanti. Dans des conditions de marché normales et compte tenu de la nature des instruments détenus (titres souverains UEMOA), le produit de la liquidation est usuellement proche du capital principal initialement versé. Toutefois, EVEREST Finance ne peut garantir la restitution intégrale du capital, en particulier dans des conditions exceptionnelles de marché (crise de liquidité, défaut souverain, événement de marché exceptionnel ou évolution défavorable des taux d\'intérêt).' },
    { type: 'heading', text: '10.4 Calcul de la valeur de rachat' },
    { type: 'paragraph', text: 'La valeur de rachat en cas de Retrait Anticipé est calculée par EVEREST Finance en tenant compte :' },
    {
      type: 'list',
      items: [
        'De la valeur de marché des actifs détenus au jour de la demande de retrait ;',
        'De la durée effective d\'immobilisation des fonds ;',
        'Des frais et commissions liés à la liquidation de la position sur le marché conformément à la Grille Tarifaire homologuée AMF-UMOA.',
      ],
    },
    { type: 'paragraph', text: 'Avant toute exécution irréversible, EVEREST Finance communique au Client une estimation détaillée du montant net à percevoir, par notification dans l\'Application. Le Client dispose alors d\'une fenêtre d\'annulation de quarante-huit (48) heures à compter de la réception de cette estimation, pendant laquelle il peut révoquer sa demande sans frais ni pénalité. À l\'expiration de la fenêtre d\'annulation, et sous réserve d\'une confirmation expresse du Client par code PIN ou validation biométrique, EVEREST Finance procède à la liquidation effective de la position dans un délai maximum de cinq (5) jours ouvrés. Passé le déclenchement de la liquidation, la demande devient irrévocable.' },
    { type: 'heading', text: '10.5 Exception - cas de force majeure' },
    { type: 'paragraph', text: 'En cas de décès du Client, d\'invalidité permanente totale dûment justifiée ou de circonstance exceptionnelle reconnue par EVEREST Finance, le Retrait Anticipé peut être accordé avec réduction ou suppression des pénalités, sur décision discrétionnaire de la Direction Générale d\'EVEREST Finance, après examen du dossier justificatif fourni par le Client ou ses ayants droit.' },
    { type: 'heading', text: 'ARTICLE 11 - GRILLE TARIFAIRE ET FRAIS' },
    { type: 'paragraph', text: 'La tarification de Sama Naffa est fixée conformément à la Grille Tarifaire d\'EVEREST Finance homologuée par l\'AMF-UMOA. Le tableau ci-après présente les principaux frais applicables. La Grille Tarifaire complète est disponible en permanence sur l\'Application.' },
    {
      type: 'table',
      headers: ['Opération / Service', 'Montant / Taux', 'Conditions'],
      rows: [
        ['Ouverture de compte', 'Gratuit', 'Versement d\'épargne'],
        ['Gratuit', 'Frais opérateur mobile à la charge du Client', 'Frais de gestion'],
        ['0,45% trimestriellement', 'Prélevés sur la capitalisation du portefeuille', 'Retrait à l\'échéance'],
        ['Gratuit', 'Frais opérateur mobile à la charge du Client', 'Retrait anticipé, gains'],
        ['Perte partielle possible', 'Selon conditions de marché au jour du retrait', 'Retrait anticipé, capital'],
        ['Produit de la liquidation', 'Sous réserve des conditions de marché', 'Cession ou liquidation de position (retrait anticipé)'],
        ['Selon grille AMF', 'Variable selon durée restante', 'Frais de valorisation'],
        ['0,25% trimestriellement', 'Prélevés sur la capitalisation du portefeuille', 'Relevé de compte'],
        ['Gratuit', 'Disponible sur l\'application', '11.1 Frais de gestion'],
        ['Les frais de gestion sont prélevés trimestriellement et sont indexés sur la capitalisation du portefeuille titres, conformément à la Grille Tarifaire homologuée.', '11.2 Commissions réglementaires', 'Des commissions réglementaires sont reversées à l\'AMF-UMOA et aux organismes de marché (DC/BR, BRVM) conformément aux textes en vigueur. Ces commissions ne sont pas intégrées dans le calcul du rendement escompté communiqué au Client.'],
      ],
    },
    { type: 'heading', text: 'ARTICLE 12 - OBJECTIFS DE RENDEMENT ET RISQUES' },
    { type: 'heading', text: '12.1 Objectifs de rendement' },
    { type: 'paragraph', text: 'EVEREST Finance communique les objectifs de rendement à titre indicatif et non contractuel. Ces objectifs sont fondés sur les performances historiques observées sur le Marché Financier Régional de l\'UEMOA et sur l\'expertise de gestion de EVEREST Finance. Ils ne constituent pas une promesse de rendement.' },
    { type: 'heading', text: '12.2 Facteurs de risque' },
    { type: 'paragraph', text: 'Le Client est informé des principaux risques inhérents au Sama Naffa : Risque de marché : les performances effectivement réalisées peuvent différer des objectifs en raison des fluctuations du Marché Financier Régional Risque de liquidité : dans des conditions exceptionnelles de marché, les délais de remboursement peuvent être allongés Risque de taux : une évolution défavorable des taux d\'intérêt peut affecter la valeur des placements Risque souverain : les placements sur les marchés de l\'UEMOA sont exposés au risque de crédit des émetteurs souverains de la zone Risque opérationnel : des incidents techniques peuvent temporairement affecter l\'accès à l\'Application ou le traitement des opérations' },
    { type: 'heading', text: '12.3 Absence de garantie du capital' },
    { type: 'paragraph', text: 'Sauf en cas de placement exclusif dans des instruments à capital garanti explicitement indiqué pour une Formule spécifique, le capital versé par le Client n\'est pas garanti. En cas de conditions de marché exceptionnellement défavorables, le Client peut recevoir un montant inférieur à sa mise initiale.' },
    { type: 'heading', text: '12.4 Performances passées' },
    { type: 'paragraph', text: 'Les performances passées du Marché Financier Régional de l\'UEMOA ou d\'EVEREST Finance ne constituent pas un indicateur fiable des résultats futurs et ne sauraient en aucun cas être assimilées à une garantie de rendement futur.' },
    { type: 'heading', text: 'ARTICLE 13 - PROTECTION DES DONNÉES PERSONNELLES' },
    { type: 'heading', text: '13.1 Responsable du traitement' },
    { type: 'paragraph', text: 'EVEREST Finance SA, en sa qualité de responsable du traitement, collecte et traite les données personnelles du Client conformément à la Loi sénégalaise N°2008-12 du 25 janvier 2008 sur la Protection des Données à Caractère Personnel et aux règlements de la Commission de Protection des Données Personnelles (CDP) du Sénégal.' },
    { type: 'heading', text: '13.2 Données collectées' },
    { type: 'paragraph', text: 'Dans le cadre de Sama Naffa, EVEREST Finance collecte les catégories de données suivantes : Données d\'identification : nom, prénom, date et lieu de naissance, nationalité, adresse Données de contact : numéro de téléphone, adresse email Données documentaires : copie de la pièce d\'identité, justificatif de domicile si requis Données financières : informations sur les sources de revenus, historique des versements et retraits, solde du compte Données de navigation et d\'utilisation de l\'Application Données LBC/FT : informations sur la profession, l\'origine des fonds, les transactions suspectes' },
    { type: 'heading', text: '13.3 Finalités du traitement' },
    { type: 'paragraph', text: 'Les données personnelles sont traitées, mais de façon non limitative, aux fins suivantes : Ouverture, gestion et clôture du Compte Client Exécution des opérations d\'épargne et de paiement Respect des obligations légales et réglementaires (KYC, LBC/FT, déclarations AMF-UMOA) Prévention et détection des fraudes et activités illicites Communication des informations réglementaires obligatoires Amélioration de Sama Naffa et personnalisation de l\'expérience utilisateur (avec consentement)' },
    { type: 'heading', text: '13.4 Base légale du traitement' },
    { type: 'paragraph', text: 'Le traitement des données repose sur : l\'exécution du contrat (CGU) pour les opérations de compte ; l\'obligation légale pour les traitements LBC/FT et KYC ; le consentement du Client pour les communications marketing.' },
    { type: 'heading', text: '13.5 Durée de conservation' },
    { type: 'paragraph', text: 'Conformément aux obligations de conservation applicables en matière de connaissance du client et de lutte contre le blanchiment, les données du Client sont conservées pendant une durée minimale de dix (10) ans à compter de la clôture du Compte Client. Les données LBC/FT sont conservées selon les délais imposés par la réglementation applicable.' },
    { type: 'heading', text: '13.6 Droits du Client' },
    { type: 'paragraph', text: 'Conformément à la Loi N°2008-12, le Client dispose des droits suivants sur ses données personnelles : Droit d\'accès : obtenir communication des données le concernant Droit de rectification : faire corriger des données inexactes Droit à l\'effacement : demander la suppression de ses données (sous réserve des obligations légales de conservation) Droit d\'opposition : s\'opposer au traitement à des fins de prospection commerciale Droit à la portabilité : recevoir ses données dans un format structuré Ces droits s\'exercent par écrit à : samanaffa@everestfin.com ou par courrier au siège social de EVEREST Finance. EVEREST Finance dispose d\'un délai de trente (30) jours calendaires pour répondre.' },
    { type: 'heading', text: '13.7 Transfert de données' },
    { type: 'paragraph', text: 'Les données personnelles du Client ne sont ni vendues, ni cédées à des tiers à des fins commerciales. Elles peuvent être transmises à l\'AMF-UMOA, à la BCEAO, aux autorités judiciaires ou aux organismes LBC/FT, dans le cadre des obligations légales et réglementaires applicables.' },
    { type: 'heading', text: '13.8 Localisation des données et sous-traitants' },
    { type: 'paragraph', text: 'Les données personnelles du Client sont hébergées sur des infrastructures pouvant être situées au Sénégal ou à l\'étranger. Tout hébergement ou transfert de données hors du Sénégal est assorti de garanties contractuelles appropriées et fait l\'objet d\'une déclaration préalable à la Commission de Protection des Données Personnelles (CDP) du Sénégal. EVEREST Finance recourt aux sous-traitants techniques suivants pour le fonctionnement de Sama Naffa :' },
    {
      type: 'list',
      items: [
        'InTouch Group (agrégation des paiements), agréé par la BCEAO ;',
        'STELLARIX, pour l\'hébergement des serveurs applicatifs et bases de données ;',
        'DiDit, pour la vérification d\'identité à distance.',
      ],
    },
    { type: 'paragraph', text: 'La liste actualisée des sous-traitants est disponible sur l\'Application et tenue à la disposition de la CDP. Chaque sous-traitant est lié à EVEREST Finance par un contrat conforme à la Loi N°2008-12 et garantissant un niveau de protection équivalent à celui assuré par EVEREST Finance elle-même. Tout transfert de données personnelles vers un pays tiers fait l\'objet d\'une déclaration préalable à la CDP et est assorti de garanties contractuelles appropriées.' },
    { type: 'heading', text: 'ARTICLE 14 - LUTTE CONTRE LE BLANCHIMENT ET LE FINANCEMENT DU TERRORISME' },
    { type: 'heading', text: '14.1 Obligations légales' },
    { type: 'paragraph', text: 'En application de la réglementation LBC/FT applicable dans l\'UEMOA, EVEREST Finance est soumise à des obligations strictes de vigilance à l\'égard de sa clientèle et de ses opérations.' },
    { type: 'heading', text: '14.2 Obligations du Client' },
    { type: 'paragraph', text: 'Le Client s\'engage à : Fournir des informations exactes et complètes sur son identité, sa profession et l\'origine de ses fonds Mettre à jour ses informations en cas de changement de situation N\'utiliser le Sama Naffa qu\'à des fins licites et légales Ne pas effectuer d\'opérations pour le compte de tiers non identifiés Répondre à toute demande d\'information complémentaire formulée par EVEREST Finance dans les délais impartis' },
    { type: 'heading', text: '14.3 Mesures de vigilance' },
    { type: 'paragraph', text: 'EVEREST Finance se réserve le droit de : Bloquer ou suspendre un Compte Client en cas d\'opérations suspectes Demander des justificatifs supplémentaires sur l\'origine des fonds versés Signaler aux autorités compétentes (Cellule Nationale de Traitement des Informations Financières, CENTIF) tout soupçon de blanchiment ou de financement du terrorisme, sans information préalable du Client Refuser ou annuler toute opération non conforme aux exigences LBC/FT Ces mesures ne peuvent engager la responsabilité de EVEREST Finance à l\'égard du Client concerné.' },
    { type: 'heading', text: 'ARTICLE 15 - RESPONSABILITÉS ET LIMITATIONS' },
    { type: 'heading', text: '15.1 Responsabilités d\'EVEREST Finance' },
    { type: 'paragraph', text: 'EVEREST Finance est responsable de la bonne exécution des opérations d\'épargne et de paiement dans les conditions définies aux présentes CGU, dans le respect de la réglementation AMF-UMOA et BCEAO applicable. EVEREST Finance s\'engage à maintenir la disponibilité de l\'Application 24h/24, 7j/7, sous réserve des opérations de maintenance planifiées annoncées avec un préavis minimum de 48 heures, sauf urgence.' },
    { type: 'heading', text: '15.2 Limitations de responsabilité' },
    { type: 'paragraph', text: 'La responsabilité de EVEREST Finance est limitée dans les cas suivants : Pertes résultant des conditions normales ou anormales du Marché Financier Régional Interruptions du service imputables aux opérateurs de télécommunications, opérateurs de monnaie électronique ou à l\'Agrégateur Conséquences d\'une utilisation non conforme de l\'Application par le Client Pertes résultant de la perte ou du vol des identifiants du Client Conséquences d\'un cas de force majeure tel que défini à l\'Article 19' },
    { type: 'heading', text: '15.3 Responsabilité du Client' },
    { type: 'paragraph', text: 'Le Client est seul responsable de l\'utilisation de son Compte Client et de la confidentialité de ses identifiants de connexion. Il s\'engage à notifier immédiatement EVEREST Finance de toute utilisation non autorisée de son Compte en contactant le service client.' },
    { type: 'heading', text: 'ARTICLE 16 - GESTION DES RÉCLAMATIONS' },
    { type: 'heading', text: '16.1 Procédure de réclamation' },
    { type: 'paragraph', text: 'Conformément à la réglementation de l\'AMF-UMOA relative au traitement des réclamations, toute réclamation du Client doit être adressée à EVEREST Finance par les voies suivantes : Via l\'Application : rubrique « Service Client / Réclamation » Par email : samanaffa@everestfin.com Par courrier : EVEREST Finance, Service Réclamations, Immeuble Platinum, 18 Bd de la République, Dakar' },
    { type: 'heading', text: '16.2 Délais de traitement' },
    { type: 'paragraph', text: 'EVEREST Finance accuse réception de toute réclamation dans un délai de quarante-huit (48) heures ouvrables. La réclamation est instruite et une réponse définitive est communiquée au Client dans un délai maximum de trente (30) jours calendaires.' },
    { type: 'heading', text: '16.3 Recours externe' },
    { type: 'paragraph', text: 'En cas d\'insatisfaction suite à la réponse de EVEREST Finance, le Client peut saisir l\'AMF-UMOA (Autorité de régulation) ou toute autre autorité compétente conformément à la réglementation en vigueur.' },
    { type: 'heading', text: 'ARTICLE 17 - RÉSILIATION ET CLÔTURE DU COMPTE' },
    { type: 'heading', text: '17.1 Résiliation à l\'initiative du Client' },
    { type: 'paragraph', text: 'Le Client peut à tout moment demander la clôture de son Compte Client via l\'Application ou par courrier écrit adressé à EVEREST Finance. La clôture entraîne la mise à disposition des fonds disponibles selon les conditions applicables, y compris les conditions de Retrait Anticipé définies à l\'Article 10 si applicable.' },
    { type: 'heading', text: '17.2 Résiliation à l\'initiative de EVEREST Finance' },
    { type: 'paragraph', text: 'EVEREST Finance peut mettre fin à Sama Naffa avec un préavis de trente (30) jours calendaires notifié au Client dans les cas suivants : Non-respect des présentes CGU Dossier KYC incomplet ou frauduleux Activités suspectes ou déclarées auprès des autorités LBC/FT Fourniture de fausses informations lors de l\'inscription Décision réglementaire de l\'AMF-UMOA ou de la BCEAO' },
    { type: 'heading', text: '17.3 Clôture immédiate' },
    { type: 'paragraph', text: 'EVEREST Finance se réserve le droit de procéder à une clôture immédiate et sans préavis du Compte Client en cas de fraude avérée, d\'utilisation illicite du Service ou de menace à la sécurité du système d\'information.' },
    { type: 'heading', text: 'ARTICLE 18 - MODIFICATION DES CONDITIONS GÉNÉRALES' },
    { type: 'paragraph', text: 'EVEREST Finance se réserve le droit de modifier les présentes CGU à tout moment, sous réserve d\'en informer le Client avec un préavis minimum de trente (30) jours calendaires avant l\'entrée en vigueur des modifications, par notification push, SMS et email. Cette notification précise la nature des modifications apportées, leur date d\'entrée en vigueur ainsi que les droits du Client en cas de refus. La poursuite de l\'utilisation de Sama Naffa après l\'entrée en vigueur des nouvelles CGU vaut acceptation tacite de celles-ci. En cas de refus des nouvelles conditions, le Client dispose du droit de clôturer son Compte selon les conditions de l’Article 17, sans application des frais de cession ou de liquidation de position prévus à l’Article 10, et d’obtenir la mise à disposition de la valeur de liquidation de son portefeuille au prix de marché à la date de clôture. Ce droit s’exerce pendant l’intégralité du délai de préavis et jusqu’à trente (30) jours après l’entrée en vigueur des nouvelles CGU.' },
    { type: 'heading', text: 'ARTICLE 19 - FORCE MAJEURE' },
    { type: 'paragraph', text: 'EVEREST Finance ne saurait être tenue responsable de tout manquement à ses obligations contractuelles résultant d\'un cas de force majeure au sens des articles 129 et suivants du Code des Obligations Civiles et Commerciales (COCC) de la République du Sénégal et des Actes Uniformes OHADA applicables, notamment : catastrophes naturelles, guerres ou conflits armés, actes terroristes, défaillance généralisée des réseaux de télécommunication ou d\'électricité, décisions gouvernementales ou réglementaires, pandémies, ou tout autre événement imprévisible, irrésistible et extérieur aux parties. Dans une telle situation, EVEREST Finance informe le Client dans les meilleurs délais par tout moyen approprié et prend toutes les mesures raisonnables pour minimiser l\'impact sur Sama Naffa et préserver les intérêts du Client.' },
    { type: 'heading', text: 'ARTICLE 20 - DROIT APPLICABLE ET JURIDICTION' },
    { type: 'heading', text: '20.1 Droit applicable' },
    { type: 'paragraph', text: 'Les présentes CGU sont soumises et interprétées conformément au droit sénégalais, aux réglementations de l\'AMF-UMOA et de la BCEAO applicables.' },
    { type: 'heading', text: '20.2 Juridiction' },
    { type: 'paragraph', text: 'En cas de litige relatif à l\'interprétation ou à l\'exécution des présentes CGU, et après tentative de résolution amiable, les parties conviennent de soumettre leur différend aux juridictions compétentes de Dakar, Sénégal.' },
    { type: 'heading', text: '20.3 Règlement amiable' },
    { type: 'paragraph', text: 'Préalablement à tout recours judiciaire, les parties s\'engagent à tenter de résoudre leur différend à l\'amiable dans un délai de soixante (60) jours calendaires à compter de la notification du litige par la partie la plus diligente.' },
    { type: 'heading', text: 'ARTICLE 21 - DISPOSITIONS FINALES' },
    { type: 'heading', text: '21.1 Intégralité de l\'accord' },
    { type: 'paragraph', text: 'Les présentes CGU, ensemble avec la Grille Tarifaire, le mandat de gestion et la Politique de Protection des Données Personnelles, constituent l\'intégralité de l\'accord entre EVEREST Finance et le Client concernant Sama Naffa.' },
    { type: 'heading', text: '21.2 Nullité partielle' },
    { type: 'paragraph', text: 'Si l\'une des dispositions des présentes CGU s\'avère nulle ou inapplicable au regard d\'une règle de droit en vigueur, elle sera réputée non écrite. Les autres dispositions demeureront pleinement en vigueur.' },
    { type: 'heading', text: '21.3 Non-renonciation' },
    { type: 'paragraph', text: 'Le fait pour EVEREST Finance de ne pas se prévaloir à un moment donné d\'une disposition des présentes CGU ne peut être interprété comme une renonciation à se prévaloir ultérieurement de cette même disposition.' },
    { type: 'heading', text: '21.4 Langue' },
    { type: 'paragraph', text: 'Les présentes CGU sont rédigées en langue française. En cas de contradiction entre une version traduite et la version française, la version française prévaut.' },
    { type: 'heading', text: '21.5 Entrée en vigueur' },
    { type: 'paragraph', text: 'Les présentes CGU entrent en vigueur à la date indiquée en page de garde et s\'appliquent à l\'ensemble des Clients ayant ouvert un compte sur la plateforme Sama Naffa, y compris aux Clients ayant adhéré antérieurement sous réserve d\'acceptation dans les conditions définies à l\'Article 18.' },
    { type: 'paragraph', text: 'Fait à Dakar, Sénégal' },
    { type: 'paragraph', text: 'EVEREST Finance SA Version 1.0, 01/06/2026' },
  ],
};
